---
- name: Check availability of SteamCMD
  shell: which steamcmd
  register: steamCheck
  ignore_errors: true
  changed_when: false

- name: Fail when SteamCMD is not available
  fail:
    msg: SteamCMD was not found on target machine.
  when: steamCheck.rc != 0

- name: Install dependencies
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - "{{ gsDependencies }}"

- name: Start and enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: true

- name: Initial install block
  block:
  - name: Open firewall ports
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
      immediate: true
    loop:
      - "{{ gsGamePort }}/tcp"
      - "{{ gsQueryPort }}/udp"

  - name: Create the game server directory
    file:
      path: "{{ gsDirectory }}"
      state: directory
      owner: "{{ gsUserName }}"
      group: "{{ gsUserGroup }}"

  - name: Install the game server files
    shell: "steamcmd +login anonymous +force_install_dir {{ gsDirectory }} +app_update {{ gsID }} validate +quit"
    args:
      executable: /bin/bash
  when: not (gsConfigChange | bool)

- name: Create the management script
  template:
    src: templates/iss_server.sh.j2
    dest: /home/steam/iss_server.sh
    owner: "{{ gsUserName }}"
    group: "{{ gsUserGroup }}"
    mode: 0770

- name: Stop the server
  shell: "/home/steam/iss_server.sh stop"
  args:
    executable: /bin/bash

# Server configuration
- name: Create a admin list
  template:
    src: templates/Admins.txt.j2
    dest: "{{ gsDirectory }}/Insurgency/Config/Server/Admins.txt"
    owner: "{{ gsUserName }}"
    group: "{{ gsUserGroup }}"
    mode: 0660
  when: gsAdminList is defined and gsAdminList | length > 0

- name: Create a map rotation list
  template:
    src: templates/MapCycle.txt.j2
    dest: "{{ gsDirectory }}/Insurgency/Config/Server/MapCycle.txt"
    owner: "{{ gsUserName }}"
    group: "{{ gsUserGroup }}"
    mode: 0660
  when: gsMapCycleList is defined and gsMapCycleList | length > 0

- name: Copy a customized Game.ini
  copy:
    src: files/custom_Game.ini
    dest:  "{{ gsDirectory }}/Insurgency/Config/Server/Game.ini"
    owner: "{{ gsUserName }}"
    group: "{{ gsUserGroup }}"
    mode: 0660
  when: gsCustomConfig | bool

- name: Start the server
  shell: "/home/steam/iss_server.sh start"
  args:
    executable: /bin/bash
